パラメータの追加 （#34）
rt-net/raspimouse2 pull request #36
Opened 2021-11-12 05:32 UTC by shu-rt

# What does this implement/fix?

# Does this close any currently open issues?

#34 の対応です。
wheel_diameter, wheel_base, PULSES_PER_REVOLUTIONの3つをROSパラメータ化しました。

# How has this been tested?

手元のロボットで動作確認を行いました。  
このとき、ロボット側の`raspimouse_ros2_examples`にあるconfig/mouse.ymlファイルに以下の3行を追加して実行しました。  
```yaml
    wheel_diameter : 0.048
    wheel_base : 0.09
    PULSES_PER_REVOLUTION : 400.0
```

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2021-11-16 01:46 UTC, ShotaAk requested changes
表記についてコメントしました。ご確認お願いします。

2021-11-16 01:46 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
毎周期`get_parameter()`を実行しているところが気になり、`get_parameter()`の実装を確認しました。
https://github.com/ros2/rclcpp/blob/e03e98220d7c4a79bfc934d43d762e017b493e9c/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L813-L831

メンバ変数にアクセスしているだけなので、毎周期`get_parameter()`を実行しても走行動作には影響しないと判断します。

2021-11-16 01:46 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +constexpr auto PULSES_PER_REVOLUTION_PARAM= "PULSES_PER_REVOLUTION";
ROSパラメータ名は小文字に、ソースコード内の定数は大文字で表記して下さい。

```suggestion
constexpr auto WHEEL_DIAMETER_PARAM = "wheel_diameter";
constexpr auto WHEEL_BASE_PARAM = "wheel_base";
constexpr auto PULSES_PER_REVOLUTION_PARAM= "pulses_per_revolution";
```

2021-11-16 01:46 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  declare_parameter(wheel_base_param, 1.0);
表記の修正

```suggestion
  declare_parameter(WHEEL_DIAMETER_PARAM, 1.0);
  declare_parameter(WHEEL_BASE_PARAM, 1.0);
```

2021-11-16 01:46 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  double wheel_base = get_parameter(wheel_base_param).get_value<double>();
表記の修正
```suggestion
  double wheel_diameter = get_parameter(WHEEL_DIAMETER_PARAM).get_value<double>();
  double wheel_base = get_parameter(WHEEL_BASE_PARAM).get_value<double>();
```

2021-11-16 01:46 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
constを付けて定数にしてください。

```suggestion
  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
```

2021-11-16 05:22 UTC, shu-rt commented on raspimouse/src/raspimouse_component.cpp
> +  auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
ありがとうございます。僕も毎周期実行する必要は特にないと判断しますので反映します

2021-11-16 05:27 UTC, shu-rt commented on raspimouse/src/raspimouse_component.cpp
> +  auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
確認ありがとうございます。  
毎周期実行する必要は特にないと思いますが、  
odometry_scale_left_wheel_paramなども毎周期呼び出されているので  
別の関数などでまとめてパラメータを呼び出すのが良さそうかなと思います。  
または、パラメータが変更される度に、コールバック関数を呼び出す方式もあります。ただ、今回のパラメータは動的に変える意味はあまりなさそうとは思います。

2021-11-16 05:30 UTC, shu-rt commented on raspimouse/src/raspimouse_component.cpp
> +constexpr auto PULSES_PER_REVOLUTION_PARAM= "PULSES_PER_REVOLUTION";
追加でほかの変数名も変更しますか？  
https://github.com/rt-net/raspimouse2/blob/ea91d066b4fc2eb3941e7489c8343acf640f1c53/raspimouse/src/raspimouse_component.cpp#L31-L34

2021-11-18 01:40 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
メカ要素のパラメータは、ノード起動時のみ変更可能にする。機能要素のパラメータ（`use_pulse_counters`、`use_light_sensors`）は実行時も変更可能にする。と、使いやすくなりそうですね。

上記の内容は、本PRの範囲を超えるので、別途issue or PRを作成しましょう。

2021-11-18 01:41 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +constexpr auto PULSES_PER_REVOLUTION_PARAM= "PULSES_PER_REVOLUTION";
これらについては、今回は変更不要です。

リファクタリングのみのPRで対応するか、https://github.com/rt-net/raspimouse2/pull/36#discussion_r751816928
の変更を実施するときについでに作業しましょう。

2021-11-18 04:57 UTC, shu-rt reviewed
LGTM

2021-11-19 01:15 UTC, ShotaAk commented
https://github.com/rt-net/raspimouse2/pull/36#discussion_r749910898
パラメータ変更のコールバックを実装しなくてくても、`get_parameter()`を実行するだけで変更されたパラメータが反映されるようなので、どのパラメータも毎周期`get_parameter()`を実行するという方針にしましょう。

2021-11-19 04:36 UTC, ShotaAk requested changes
ラズパイマウスの実機で動作確認しました。
指摘事項の修正をお願いします。

また、今回増えたパラメータについて、READMEに説明を追記して下さい。

---
以下、確認方法。

```sh
# ラズパイマウス上で実行
$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py joyconfig:=f710

# リモートPC上で実行（odomを描画するため）
$ ros2 launch raspimouse_ros2_examples slam.launch.py
```

下記のようにパラメータをセットし、操作量に対するodomの変化量が変わることを確認しました。

```sh
$ ros2 param set /raspimouse wheel_diameter 0.048
$ ros2 param set /raspimouse wheel_base 0.09
```

また、`pulses_per_revolution`については、`use_pulse_counter`をtrueにした状態で動作確認しました。

https://github.com/rt-net/raspimouse_ros2_examples/blob/master/config/mouse.yml

2021-11-19 04:36 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  declare_parameter(PULSES_PER_REVOLUTION_PARAM, 1.0);
パラメータの初期値が変わっていたので修正お願いします。

```suggestion
  declare_parameter(WHEEL_DIAMETER_PARAM, 0.048);
  declare_parameter(WHEEL_BASE_PARAM, 0.09);
  declare_parameter(PULSES_PER_REVOLUTION_PARAM, 400.0);
```

2021-11-19 06:14 UTC, ShotaAk requested changes
確認漏れがありました。修正お願いします。

2021-11-19 06:14 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
定数を大文字化したいです。
関係するところも修正お願いします。

```suggestion
  const auto WHEEL_DIAMETER = get_parameter(WHEEL_DIAMETER_PARAM).get_value<double>();
  const auto WHEEL_TREAD = get_parameter(WHEEL_TREAD_PARAM).get_value<double>();
  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
```

2021-11-19 06:20 UTC, shu-rt commented on raspimouse/src/raspimouse_component.cpp
> +  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
以下のコミットで対応しました。
5fd68b8

2021-11-19 06:31 UTC, ShotaAk commented on raspimouse/src/raspimouse_component.cpp
> +  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
反映し忘れです。
```suggestion
  const auto WHEEL_DIAMETER = get_parameter(WHEEL_DIAMETER_PARAM).get_value<double>();
  const auto WHEEL_TREAD = get_parameter(WHEEL_TREAD_PARAM).get_value<double>();
  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
```

2021-11-19 06:33 UTC, shu-rt commented on raspimouse/src/raspimouse_component.cpp
> +  const auto PULSES_PER_REVOLUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
すみません、見落としていました

2021-11-19 06:34 UTC, ShotaAk approved these changes
LGTM

2021-11-19 06:34 UTC, merged