Humble対応
rt-net/raspimouse2 pull request #48
Opened 2023-01-17 09:17 UTC by shu-rt

# What does this implement/fix?

`ROS 2 Humble`に対応するように変更を加えました。

# Does this close any currently open issues?

No

# How has this been tested?

ラズパイマウス（Raspi4, Ubuntu 20.04, Docker Humble）を用いて動作確認を行いました

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-01-19 05:04 UTC, ShotaAk commented
https://github.com/rt-net/raspimouse2/pull/47
の変更内容も実施していただけますか？

2023-01-19 05:10 UTC, Tiryoh commented
#47 のPull Requestのbase branchを`feature/support-humble`に変更します

2023-01-19 05:16 UTC, ShotaAk requested changes
コメントの確認お願いします。

2023-01-19 05:16 UTC, ShotaAk commented on README.md
> +| **TODO** | **TODO** |
foxyにも対応していることを明記したいので、foxyに関する情報はそのままでお願いします。

2023-01-19 05:16 UTC, ShotaAk commented on README.md
> +  - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
foxyにも対応していることを明記したいので、foxyに関する情報はそのままでお願いします。

例えば下記のように変更するのはどうでしょうか？

- Foxy Fitzroy for `foxy-devel`
- Humble Hawksbill for `humble-devel`

2023-01-19 05:50 UTC, shu-rt commented on README.md
> +  - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
上記の修正と合わせて、一個のひょうにまとめました。
インストール手順へのリンクはもとに戻しました

2023-01-20 01:24 UTC, ShotaAk approved these changes
良いと思います。

PRのDescriptionに、使用したDockerイメージ名、実行したコマンド、何を確認したのか、を追記お願いします。

2023-01-25 01:06 UTC, merged