ROS 2 Jazzyへの対応
rt-net/raspimouse2 pull request #53
Opened 2024-10-17 05:28 UTC by KuraZuzu

# What does this implement/fix?

ROS 2 Jazzyに対応させます。

# Does this close any currently open issues?

しません。

# How has this been tested?

以下の環境を用意し、動作確認をしました。

## 環境

- Raspberry Pi 4B (4GB)
- Ubuntu Server 24.04 LTS
- ROS 2 Jazzy Base

## 環境確認

実機で構築した環境をコマンドで確認します。

```bash
$ uname -a
Linux ubuntu 6.8.0-1012-raspi #13-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  2 11:13:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

## 動作確認

以下の手順で動作することを確認しました。

```bash
# Terminal 1
予めデバイスドライバをビルド・インストールしておく

$ source ~/ros2_ws/install/setup.bash
$ ros2 run raspimouse raspimouse

# Terminal 2
$ source ~/ros2_ws/install/setup.bash
$ ros2 lifecycle set raspimouse configure

# Set buzzer frequency
$ ros2 topic pub -1 /buzzer std_msgs/msg/Int16 '{data: 1000}'
$ ros2 topic pub -1 /buzzer std_msgs/msg/Int16 '{data: 0}'

# Transition to active state
$ ros2 lifecycle set raspimouse activate

# View lightsensors status
$ ros2 topic echo /light_sensors

# View SW statussudo 
$ ros2 topic echo /switches

# Toggle LEDs
$ ros2 topic pub -1 /leds raspimouse_msgs/msg/Leds '{led0: 0, led1: 1, led2: 0, led3: 1}'
$ ros2 topic pub -1 /leds raspimouse_msgs/msg/Leds '{led0: 1, led1: 0, led2: 1, led3: 0}'
$ ros2 topic pub -1 /leds raspimouse_msgs/msg/Leds '{led0: 0, led1: 0, led2: 0, led3: 0}'

# Rotate motors
$ ros2 service call /motor_power std_srvs/SetBool '{data: true}'
$ ros2 topic pub -1 /cmd_vel geometry_msgs/msg/TwistStamped '{twist: {linear: {x: 0.05, y: 0, z: 0}, angular: {x: 0, y: 0, z: 0.05}}}'
$ ros2 topic pub -1 /cmd_vel geometry_msgs/msg/TwistStamped '{twist: {linear: {x: 0, y: 0, z: 0}, angular: {x: 0, y: 0, z: 0}}}
$ ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -p stamped:=true
$ ros2 lifecycle set raspimouse deactivate
```

# Any other comments?

## 主な変更点

* ドキュメントを修正しました
* リポジトリのRaspberry Pi Mouseの画像リンクを修正しました
* `/cmd/vel`のメッセージの型を`Twist`か`TwistStamped`変更しました
* `/cmd_vel`の変更により後方互換性がなくなったため、メジャー番号をアップデートしました

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-10-17 05:54 UTC, YusukeKato commented
動作確認を`ros2 run raspimouse raspimouse`で行っていますが、`ros2 launch raspimouse raspimouse.launch.py`でlaunchファイルから実行しても問題ないか確認をお願いいたします（launchファイルからノードを起動して`ros2 lifecycle set raspimouse configure`や`ros2 lifecycle set raspimouse activate`を実行しなくてもactivateの状態になるか確認をお願いいたします）。

2024-10-17 06:02 UTC, YusukeKato commented
CHANGELOG.rstの更新とpackage.xmlのバージョンの更新はパッケージのリリース時に行ったほうが分かりやすいので、このPRでは変更なしでお願いいたします。
Humble版リリース時のPRの参考：https://github.com/rt-net/raspimouse2/pull/49/files

2024-10-17 06:49 UTC, KuraZuzu commented
レビューに沿って以下の点を修正しました。
- launchファイルからの起動でも動作すること確認し、PRの本文の手順にも反映しました
- package.xmlのバージョン変更を取り消しました
- CIが無効化されていなかったので有効にしました

2024-10-17 07:28 UTC, YusukeKato requested changes
コメントの確認をお願いいたします。

2024-10-17 07:28 UTC, YusukeKato commented on README.md
> +$ ros2 lifecycle set raspimouse configure
launchファイルからノードを起動した場合、`ros2 lifecycle set raspimouse *`のコマンド2行が不要なら削除をお願いいたします。

2024-10-17 07:29 UTC, YusukeKato commented
CIが失敗しているので確認をお願いいたします。
またCIの設定がHumbleのままになっていそうなのでJazzyへ変更をお願いいたします。

2024-10-18 06:04 UTC, KuraZuzu commented on README.md
> +$ ros2 lifecycle set raspimouse configure
削除しました。

2024-10-18 06:05 UTC, KuraZuzu commented
CIで指摘されていた構文へのエラーを修正しました

2024-10-18 06:06 UTC, KuraZuzu commented
ご指摘の点を全て修正したので、ご確認よろしくおねがいします。

2024-10-22 08:56 UTC, YusukeKato commented
実機のRaspberry Pi Mouseで動作確認できました。

2024-10-23 01:18 UTC, YusukeKato requested changes
コメントの確認をお願いいたします。

2024-10-23 01:18 UTC, YusukeKato commented on README.md
> +$ source ~/ros2_ws/install/setup.
```suggestion
$ source ~/ros2_ws/install/setup.bash
```

拡張子が消えているので追記をお願いいたします。

2024-10-23 01:33 UTC, YusukeKato requested changes
actions/checkoutの更新&確認をお願いいたします。

2024-10-23 01:33 UTC, YusukeKato commented on .github/workflows/industrial_ci.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

actions/checkoutの最新バージョンが4になっているみたいなので更新してCIが通るか確認をお願いいたします。
https://github.com/marketplace/actions/checkout

2024-10-23 01:54 UTC, KuraZuzu commented
コメントありがとうございます。以下の2点について修正しました。
- README.mdで記入漏れのあった.bash拡張子の補完
- actions/checkoutのバージョンを3から4にアップデート

2024-10-23 01:57 UTC, YusukeKato commented
LGTMです！

2024-10-23 01:57 UTC, merged