ROS 2 RollingのCI設定の追加
rt-net/raspimouse2 pull request #55
Opened 2024-11-01 04:58 UTC by KuraZuzu

# What does this implement/fix?

ROS 2 RollingのCI設定を追加します。

# Does this close any currently open issues?

しません。

# How has this been tested?

CIが通ることを確認しました。

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-11-01 05:09 UTC, Kuwamai requested changes
一点コメントしました

2024-11-01 05:09 UTC, Kuwamai commented on .github/workflows/industrial_ci.yml
>      strategy:
RollingのCIで失敗するとJazzyのCIが始まらなくなってしまうので、下記のPRを参考に設定の追加お願いします。
https://github.com/rt-net/rt_manipulators_cpp/pull/34/files
```suggestion
    strategy:
        fail-fast: false
```

2024-11-01 07:26 UTC, KuraZuzu commented
レビューありがとうございます。追加しました。

2024-11-01 07:47 UTC, YusukeKato requested changes
コメントのご確認をお願いいたします。

2024-11-01 07:47 UTC, YusukeKato commented on .github/workflows/industrial_ci.yml
> +        fail-fast: false
インデントがずれてCIが通っていなさそうです。

2024-11-01 08:18 UTC, KuraZuzu commented on .github/workflows/industrial_ci.yml
> +        fail-fast: false
レビューありがとうございます。修正しました。

2024-11-05 01:16 UTC, Kuwamai commented
> レビューありがとうございます。追加しました。

この部分に関してはレビューOKです。

2024-11-05 01:18 UTC, YusukeKato commented
CIのチェックが通っていることを確認しました。
LGTMです！

2024-11-05 01:18 UTC, merged